{
 "title": "NYC Taxi Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Volume de Courses par Heure (Batch)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT hour, trip_count FROM kpi_hourly_stats ORDER BY hour ASC"
    }
   ]
  },
  {
   "title": "Top Zones (Batch)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM kpi_zone_stats ORDER BY trip_count DESC LIMIT 20"
    }
   ]
  },
  {
   "title": "Streaming Feed: Réel vs Prédiction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT tpep_pickup_datetime as time, total_amount as real_price, prediction as predicted_price FROM streaming_predictions WHERE $__timeFilter(tpep_pickup_datetime)"
    }
   ]
  }
 ]
}